<a href="https://colab.research.google.com/github/dnldes/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

In [35]:
# A+B+C =89
# if A = C-6
# C-6 + 3C + C = 89
# 5C = 89+6
# 5C = 95/5
# C = 19
# B = 3C = 3*19 = 57
# Going back A+B+C 
# = 13 + 57 + 19 = 89
A = 13
B = 57
C= 19
print(A+B+C)

89


### Problem 2 error requires singular matrix. Getting its determinant matrix will result into a zero value, then it cannot be inversed

In [39]:
#proving
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)

print(round(np.linalg.det(A)))

inv_A = np.linalg.inv(A)
print(inv_A)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
0


LinAlgError: ignored

In [36]:
(A = np.array([[8,5,-6],[-12,9,12],[-3,-3,5]])
k,l = np.linalg.eig(A)
print("The Eigenvalues are: ")
print(k.round())
print()
print("The Eigenvectors are: ")
print(l.round())


The Eigenvalues are: 
[10.+10.j 10.-10.j  2. +0.j]

The Eigenvectors are: 
[[-0.-0.j -0.+0.j  1.+0.j]
 [ 1.+0.j  1.-0.j -0.+0.j]
 [ 0.+0.j  0.-0.j  1.+0.j]]
