<a href="https://colab.research.google.com/github/dnldes/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python program to inverse

In [25]:
import numpy as np

C = np.array([[1,2],[4,7]])

invC = (np.linalg.inv(C))
print(invC)

[[-7.  2.]
 [ 4. -1.]]


In [26]:
DT = np.dot(A,invC)
print(C)

[[1 2]
 [4 7]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
##Python program to inverse a 3x3 Matrix A = ([6,1,1],[4,-2,5],[2,8,7])

A = np.array([[6,1,1],[4,-2,5],[2,8,7]])

B = (np.linalg.inv(A))
print(B)



[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [38]:
prd = np.dot(A,B)
print(prd)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]
