<a href="https://colab.research.google.com/github/dnldes/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python program to inverse

In [ ]:
import numpy as np

C = np.array([[1,2],[4,7]])

invC = (np.linalg.inv(C))
print(invC)

[[-7.  2.]
 [ 4. -1.]]


In [ ]:
DT = np.dot(A,invC)
print(C)

[[1 2]
 [4 7]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
##Python program to inverse a 3x3 Matrix A = ([6,1,1],[4,-2,5],[2,8,7])

A = np.array([[6,1,1],[4,-2,5],[2,8,7]])

B = (np.linalg.inv(A))
print(B)



[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
prd = np.dot(A,B)
print(prd)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


In [47]:
##Python Program to Inverse a 3x3 Matrix A = ([6,1,1],[4,-2,5],[2,8,7])
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A,"\n")
B = np.transpose(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] 

[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


#Coding Activity 3

In [46]:
# Create a Python Program to inverse and transpose a 4x4 matrix, A = ( [6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7] )

print("Inverse")
invA = np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
inA = (np.linalg.inv(invA))
print(inA)

print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")

print("Transpose")
trA = np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
print(trA)

Inverse
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
Transpose
[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
