<a href="https://colab.research.google.com/github/dnldes/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [5]:
import numpy as np       #library numpy for the process of solving arrays

L5 = np.zeros((5,5))     #creates a 5x5 array containing zeroes(0)
print(L5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


###Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [68]:
Q2 = np.array([[1,1,1],[0,1,1],[0,0,1]]) 
diagonal = np.triu(Q2) #code to get the values from the upper triangle
print(diagonal)

[[1 1 1]
 [0 1 1]
 [0 0 1]]


###Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [61]:
Default = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(Default)
print("------------------")
Symmetric = np.transpose(Default)
print(Symmetric)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------
[[0 3 6]
 [1 4 7]
 [2 5 8]]


###Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [18]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #variable C is declared for the matrix
inv_C = np.linalg.inv(C)                 #function to compute the inverse of the matrix C
print(inv_C)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


###Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [16]:
D = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(D)
print()

print(round(np.linalg.det(D)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

5


###Question 6. Find the roots of the linear equations by showing its python codes (30 points)

In [59]:
print("given: ")
print("5X1 + 4X2 + X3 = 3.4")
print("10X1 + 9X2 + 4X3 = 8.8")
print("10X1 + 13X2 + 15X3 = 19.2")
print()

print("Find the roots X")
print("------------------")
#create arrays
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
Answers = np.array([[3.4],[8.8],[19.2]])
print(A)
print("------------------")
print(Answers)
print("------------------")
print("Inverse of A")
inv_A = np.linalg.inv(A)
print(inv_A)
print("------------------")
print("Get the dot product of inv_A and Answers to find the roots")
print("------------------")


#code to find the roots
FRLE = inv_A.dot(Answers)
print("These are the roots of 'X' ")
print(FRLE)

#proving
print("To prove roots of X are correct")
#input the roots to all "x" variables

X1 = 0.2 
X2 = 0.4 
X3 = 0.8

print(5*X1 + 4*X2 + X3)
print(10*X1 + 9*X2 + 4*X3)
print(10*X1 + 13*X2 + 15*X3)

given: 
5X1 + 4X2 + X3 = 3.4
10X1 + 9X2 + 4X3 = 8.8
10X1 + 13X2 + 15X3 = 19.2

Find the roots X
------------------
[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
------------------
[[ 3.4]
 [ 8.8]
 [19.2]]
------------------
Inverse of A
[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
------------------
Get the dot product of inv_A and Answers to find the roots
------------------
These are the roots of 'X' 
[[0.2]
 [0.4]
 [0.8]]
To prove roots of X are correct
3.4000000000000004
8.8
19.2
