<a href="https://colab.research.google.com/github/dnldes/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem 1. Consider the four matrices.

In [41]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

dot = np.dot(A,B)
print(dot)

[[22 28]
 [49 64]]


In [36]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

sum = D + D
print(sum)

[[2 4]
 [6 8]]


In [33]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

Sc = 2*C
print(Sc)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


#Problem 2 Given the linear combination below, try to create a corresponding matrix representing it and display its type, shape, and its dimension.

In [58]:
T = np.array([5,3,-1])

print(T)
print("Type:     ", T.dtype)
print("Size:      ", T.size)
print("Shape:    ", T.shape)
print("Dimension: ", T.ndim)

[ 5  3 -1]
Type:      int64
Size:       3
Shape:     (3,)
Dimension:  1
