<a href="https://colab.research.google.com/github/dnldes/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question 1

In [23]:
import numpy as np
C = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print(C)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#Question 2




In [24]:
Double = 2*C  #Formula that doubles the value of each element
print(Double)

[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]


#Question 3

In [18]:
A = np.array([2,7,4])
B = np.array([3,9,8])

CP = np.cross(A,B)  #Formula for computing cross product of A and B
CP

array([20, -4, -3])